//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAPCA.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAPCA.res.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add edu app.
        /// </summary>
        internal static string AddEduAppButton {
            get {
                return ResourceManager.GetString("AddEduAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game app.
        /// </summary>
        internal static string AddGameAppButton {
            get {
                return ResourceManager.GetString("AddGameAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App killing.
        /// </summary>
        internal static string AppKillingCheckBox {
            get {
                return ResourceManager.GetString("AppKillingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete edu app.
        /// </summary>
        internal static string DeleteEduAppButton {
            get {
                return ResourceManager.GetString("DeleteEduAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete game app.
        /// </summary>
        internal static string DeleteGameAppButton {
            get {
                return ResourceManager.GetString("DeleteGameAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education apps limit.
        /// </summary>
        internal static string EduAppLimitLabel {
            get {
                return ResourceManager.GetString("EduAppLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitTrayMenu {
            get {
                return ResourceManager.GetString("ExitTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game apps limit.
        /// </summary>
        internal static string GameAppLimitLabel {
            get {
                return ResourceManager.GetString("GameAppLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game apps are blocked until you finish your educational time ({0}) min.
        /// </summary>
        internal static string GameAppsBlocked_Text {
            get {
                return ResourceManager.GetString("GameAppsBlocked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Apps Blocked.
        /// </summary>
        internal static string GameAppsBlocked_Title {
            get {
                return ResourceManager.GetString("GameAppsBlocked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed your educational time limit. Game apps are now unlocked.
        /// </summary>
        internal static string GameAppsUnlocked_Text {
            get {
                return ResourceManager.GetString("GameAppsUnlocked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Apps Unlocked.
        /// </summary>
        internal static string GameAppsUnlocked_Title {
            get {
                return ResourceManager.GetString("GameAppsUnlocked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You`ve exceeded your time limit for games ({0} minutes).
        /// </summary>
        internal static string GameTimeLimit_Text {
            get {
                return ResourceManager.GetString("GameTimeLimit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game time limit exceeded.
        /// </summary>
        internal static string GameTimeLimit_Title {
            get {
                return ResourceManager.GetString("GameTimeLimit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill all game apps.
        /// </summary>
        internal static string KillAllGamesButton {
            get {
                return ResourceManager.GetString("KillAllGamesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginWindow {
            get {
                return ResourceManager.GetString("LoginWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Try Again..
        /// </summary>
        internal static string LoginWindow_button1_Click_Incorrect_password {
            get {
                return ResourceManager.GetString("LoginWindow_button1_Click_Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window: {0}.
        /// </summary>
        internal static string MainWindow_UpdateInfo_Active_Window {
            get {
                return ResourceManager.GetString("MainWindow_UpdateInfo_Active_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are games unlocked? :{0}.
        /// </summary>
        internal static string MainWindow_UpdateInfo_Are_games_unlocked {
            get {
                return ResourceManager.GetString("MainWindow_UpdateInfo_Are_games_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education apps used time:{0} min.
        /// </summary>
        internal static string MainWindow_UpdateInfo_Education_apps_used_time {
            get {
                return ResourceManager.GetString("MainWindow_UpdateInfo_Education_apps_used_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game apps  used time:{0} min.
        /// </summary>
        internal static string MainWindow_UpdateInfo_Game_apps__used_time {
            get {
                return ResourceManager.GetString("MainWindow_UpdateInfo_Game_apps__used_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Date:{0:yyyy MMMM dd}.
        /// </summary>
        internal static string MainWindow_UpdateInfo_System_Date {
            get {
                return ResourceManager.GetString("MainWindow_UpdateInfo_System_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenTrayMenu {
            get {
                return ResourceManager.GetString("OpenTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set limits.
        /// </summary>
        internal static string SetLimitButton {
            get {
                return ResourceManager.GetString("SetLimitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
    }
}
